name: Test and Security
on: [push]
jobs: 
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.4.0
        - name: Cypress.io
          uses: cypress-io/github-action@v2.9.7
          with:
            start: yarn run

    security:
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
       env:
          SNYK_TOKEN: 'e936a40a-2766-4824-89bb-ece45b46b5a0'
               
