name: Cypress test
on: [push]
jobs: 
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.4.0
        - name: Cypress.io
          uses: cypress-io/github-action@v2.9.7
        - name: Snyk
          uses: snyk/actions@0.3.0

          with:
            start: yarn run

  
