name: Security
on: [push]
  jobs: 
    snyk-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.4.0
        - name: Snyk
          uses: snyk/actions@0.3.0
          with:
            start: snyk monitor

    